# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: jauregao
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: hello
# "service" is the name of this project. This will also be added to your AWS resource names.
service: first-aws-project

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: hello-world
        method: get
        cors: true
